# Generated by Django 4.1.7 on 2023-02-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonvoyage_app', '0004_bookmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=30)),
                ('spots', models.CharField(max_length=500)),
                ('food', models.CharField(max_length=30)),
                ('pet', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30)),
                ('cab', models.CharField(max_length=30)),
                ('stay', models.CharField(max_length=30)),
                ('rate', models.CharField(max_length=30)),
            ],
        ),
    ]
